### ISSUE TITLE
Cannot Add Ore

### ISSUE THREAD

**Issue by Axacution** [MichaelHillcox/XRay-Mod#38] opened 2018-03-21 01:17 UTC
Using MC version 1.10.2 and mod version 1.3.1. 
![xraybug2](https://user-images.githubusercontent.com/37603470/37690854-20dec726-2c84-11e8-83c7-8b012d96a989.PNG)
![xraybug3](https://user-images.githubusercontent.com/37603470/37690855-20e8d7a2-2c84-11e8-9f7f-2fba297fca10.PNG)
![xraybug4](https://user-images.githubusercontent.com/37603470/37690856-20f69f5e-2c84-11e8-8430-ec7b1a0bf18b.PNG)
![xraybug1](https://user-images.githubusercontent.com/37603470/37690857-2103d66a-2c84-11e8-8a88-d5ce613feb50.PNG)

**Comment by MichaelHillcox** [comment] 2018-03-21 09:52
Thanks you for letting me know of this issue. Have you tried doing 6410:0 or 6410 as just the id. Could you put a screenshot of the add gui with no text inputed? I've not used the mod in a while for that version.

**Comment by MichaelHillcox** [comment] 2018-03-29 21:29
Going to close this because I'm pretty sure the issue is with the / and not the mod it's self

**Closed by MichaelHillcox** 2018-03-29 21:29 UTC
Labels: bug, legacy
