### ISSUE TITLE
[1.12] NullPointerException - drawOres

### ISSUE THREAD

**Issue by Symbai** [MichaelHillcox/XRay-Mod#21] opened 2017-07-31 10:17 UTC
I left my minecraft singleplayer opened and today noticed that it has crashed. Here is the log:

```
java.lang.NullPointerException: Unexpected error
	at com.fgtxray.client.RenderTick.drawOres(RenderTick.java:82)
	at com.fgtxray.client.RenderTick.onWorldRenderLast(RenderTick.java:42)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_526_RenderTick_onWorldRenderLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:160)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1421)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1250)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1053)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by MichaelHillcox** [comment] 2017-07-31 18:43
Duplicate of #19

**Closed by MichaelHillcox** 2017-07-31 18:43 UTC
Labels: bug
